name: ManCom
version: ${project.version}
main: red.man10.mancom.ManCom
commands:
  ms:
    description: Command no setsumei
    usage: /<command>
    default: true
permissions:
  mancom.op:
    default: OP